[workspace]
members = [
    "lib",
    "Icr",
    "Liquid",
    "Real_time_ltv",
    "program",
    "script",
    
    
    "BimaOccumPutCall"
]
resolver = "2"

[workspace.dependencies]
alloy-sol-types = "1.0"
